from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(912, 535)
        icon = QIcon(QIcon.fromTheme(u"Pits"))
        Dialog.setWindowIcon(icon)
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(320, 20, 91, 51))
        font = QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton_2 = QPushButton(Dialog)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(480, 20, 91, 51))
        self.pushButton_2.setFont(font)
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(30, 120, 661, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(Dialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(30, 240, 661, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(Dialog)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(30, 360, 661, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(Dialog)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(30, 500, 661, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(700, 131, 121, 20))
        self.label.setFont(font)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(700, 250, 121, 21))
        self.label_2.setFont(font)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(700, 380, 141, 16))
        self.label_3.setFont(font)
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(700, 171, 121, 20))
        self.label_7.setFont(font)
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(700, 291, 121, 20))
        self.label_8.setFont(font)
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(700, 420, 121, 21))
        self.label_9.setFont(font)
        self.carro1 = QPushButton(Dialog)
        self.carro1.setObjectName(u"carro1")
        self.carro1.setGeometry(QRect(40, 130, 300, 115))
        self.carro2 = QPushButton(Dialog)
        self.carro2.setObjectName(u"carro2")
        self.carro2.setGeometry(QRect(40, 250, 300, 115))
        self.carro3 = QPushButton(Dialog)
        self.carro3.setObjectName(u"carro3")
        self.carro3.setGeometry(QRect(40, 380, 300, 115))
        self.ganador1 = QLabel(Dialog)
        self.ganador1.setObjectName(u"ganador1")
        self.ganador1.setGeometry(QRect(450, 180, 181, 20))
        self.ganador1.setFont(font)
        self.ganador2 = QLabel(Dialog)
        self.ganador2.setObjectName(u"ganador2")
        self.ganador2.setGeometry(QRect(450, 300, 181, 20))
        self.ganador2.setFont(font)
        self.ganador3 = QLabel(Dialog)
        self.ganador3.setObjectName(u"ganador3")
        self.ganador3.setGeometry(QRect(450, 420, 181, 20))
        self.ganador3.setFont(font)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Pits", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Iniciar", None))
        self.pushButton_2.setText(QCoreApplication.translate("Dialog", u"Reiniciar", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Estado: ", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Estado: ", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Estado: ", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Vueltas:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Vueltas:", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Vueltas:", None))
        self.ganador1.setText("")
        self.ganador2.setText("")
        self.ganador3.setText("")

        self.carro1.setStyleSheet('background-image:url(img/indice.png); background-color:#ffffff')
        self.carro2.setStyleSheet('background-image:url(img/output.png); background-color:#ffffff')
        self.carro3.setStyleSheet('background-image:url(img/output1.png); background-color:#ffffff')